site_name: Kmutnb Docker container
theme:
  logo: assets/logo.png
  name: material
  font:
    text: IBM Plex Sans Thai Looped
  features:
    - navigation.top
    - navigation.footer
    
nav:
  - Home: index.md
  - Book:
    - 1. Fundamentals: book/01-fundamentals.md
    - 2. Installation: book/02-installation.md
    - 3. Basic Operations: book/03-basic-operations.md
    - 4. Dockerfile: book/04-dockerfile.md
    - 5. Docker Compose: book/05-docker-compose.md
    - 6. Advanced: book/06-advanced.md
    - 7. Workshop Basic: book/07-workshop-basic.md
    - 8. Workshop Webserver: book/08-workshop-webserver.md
    - 9. Workshop Fullstack: book/09-workshop-fullstack.md
    - 10. Cgroups, Namespaces & Security: book/10-cgroups-namespaces-security.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

copyright: Copyright &copy; 2025 sawangpong muadphet